version: "3.7"

services:
  ombinotify:
    container_name: ombinotify
    build: ./notify/
    restart: unless-stopped
    ports:
        - 5000:5000
  requestbot:
    container_name: requestbot
    build: ./slackbot/
    restart: unless-stopped
    ports:
      - 3001:3001
